title = "Amy O'neill"
baseURL = "https://amyxon.github.io/Portfolio/"
relativeURLs = true
canonifyURLs = false 
uglyURLs = true
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Carlow, IE"
email = "amyoneill10@proton.me"
favicon = "/favicon.ico"
firstName = "Amy"
lastName = "ONeill"
phone = "353 (89) 475 3664"
profileImage = "img/Amytest.png"
showQr = true
showContact = false
showBoards  = true
showCertifications = true
showSocializations = true
sections = ["skills","education","projects", "futureprojects"]
vcardfields = [
    "name",
    "image",
    "org",
    "email",
    "workemail",
    "phone",
    "url",
    "title"
]

[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/amy-o-neill-2093b03b1/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/amyxon"


[outputs]
home = ["HTML", "JSON"]
page = ["HTML", "vcard"]

[taxonomies]
tag = "tags"


[mediaTypes]
  [mediaTypes."text/vcard"]
    suffixes = ["vcf"]

[outputFormats]
  [outputFormats.VCard]
    mediaType = "text/vcard"
    baseName = "contact"
    isPlainText = true
    notAlternative = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
